# -*- coding: utf-8 -*-
"""load&inspects

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1odcu19yHcr5Ciw1KPrYiHhGhBYJPy2Jl
"""

import pandas as pd
import os

# --- Load your file ---
file_path = "sample_data/california_housing_train.csv"  # Change to your file: .csv, .xlsx, .json, etc.

ext = os.path.splitext(file_path)[1].lower()

if ext == ".csv":
    df = pd.read_csv(file_path)
elif ext in (".xlsx", ".xls"):
    df = pd.read_excel(file_path)
elif ext == ".json":
    df = pd.read_json(file_path)
else:
    raise ValueError(f"Unsupported file type: {ext}")

# --- Inspect ---
print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nData Types:\n", df.dtypes)
print("\nFirst 5 rows:\n", df.head())
print("\nMissing Values:\n", df.isnull().sum())
print("\nBasic Stats:\n", df.describe(include="all"))